alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias g='git'
alias gm='git commit -m'
alias gb='git branch -vv'
alias gs='git status'
alias gst='git status'
alias gd='git diff'
alias gds='git diff --staged'
alias gff='git merge --ff-only @{u}'
alias gp='git push'
alias gu='git pull'
alias gl='git log'
alias gh='git hist'
alias gco='git checkout'
